[input]
source_dir = "src-tauri/src"
exclude = [
    "tests",
    "target",
]
use_cargo_expand = false

[output]
types_file = "src/bindings/_Structs.ts"
commands_file = "src/bindings/_Commands.ts"

[naming]
type_prefix = ""
type_suffix = ""
function_prefix = ""
function_suffix = ""
